# Site informations
name: 'Bertrand Keller'
title: "✊&nbsp;Bertrand Keller"
email: bertrand.keller@gmail.com
description: Sites statiques et Low-Tech
subject: Histoire de gestion de contenu, générateur de site internet statique, éco-conception et Low-Tech

# Site settings
baseurl: ""
permalink: /:year/:month/:day/:title/
url: "https://bertrandkeller.info"
lang: fr
timezone: Europe/Paris
mainColor: '#111111'
incremental: true
profile: true
encoding: utf-8
repository: bertrandkeller/bertrandkeller.github.io

robot: index,follow

cloudinary:
  cloud_name: dou0m7u5s
  only_prod: true
  verbose: true
  #origin_url: https://bertrandkeller.info
  attributes:
    loading: "lazy"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width:40em) 40em, 90vw"

# seo-tag
author: Bertrand Keller
logo: /assets/bertrandkeller.png
image:
  path: /assets/bertrandkeller.png
  height: 200
  width: 200
twitter:
  username: bertrandkeller
social:
  type: personn
  name: Bertrand Keller
  links:
    - https://twitter.com/bertrandkeller
    - https://github.com/bertrandkeller

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  casestudies:
    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      publisher: Bertrand Keller
  - scope:
      path: ""
      type: casestudies
    values:
      layout: page
  - scope:
      path: "liens"
    values:
      layout: links

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: feed

text:
  pagination:
    newer: 'Précédent'
    older: 'Suivant'


# Webmention
webmentions:
  debug: true
  username: bertrandkeller
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - links
  js: false
  legacy_domains:
    - http://bertrandkeller.info
  throttle_lookups:
    #   last_week: daily
    last_month: daily
    last_year: weekly
    older: every 2 weeks

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-tidy
  - jekyll-twitter-plugin

include:
  - _redirects
  - _headers

exclude:
  - .cache
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE.md
  - README.md
  - dploy.yml
  - LICENSE
  - node_modules

jekyll_tidy:
  compress_html: true
  exclude: ["sw.js","404.html","offline.md"]
