force=true
[[headers]]
  for = "/*"

  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# https://dev.to/philw_/using-a-netlify-edge-worker-to-cut-down-on-header-bloat-by-removing-html-only-headers-from-your-static-assets-3nh9
[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"
